%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"


#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# --- Câmera 1 (Esquerda) - Extraído de image_1040e2.png ---
# Erro RMS da calibração: 0.1399
Camera1.fx: 405.8420
Camera1.fy: 404.9674
Camera1.cx: 388.7755
Camera1.cy: 299.1945
# Coeficientes de distorção Radial (k1, k2, k3) e Tangencial (p1, p2)
Camera1.k1: -0.0409
Camera1.k2: 0.0839
Camera1.k3: -0.0404
Camera1.p1: -0.00025170  
Camera1.p2: -0.0005388 # -4.2738e-04

# --- Câmera 2 (Direita) - Extraído de image_1040c2.png ---
# Erro RMS da calibração: 0.1191
Camera2.fx: 403.6925
Camera2.fy: 402.9813
Camera2.cx: 389.6617
Camera2.cy: 300.9383
# Coeficientes de distorção Radial (k1, k2, k3) e Tangencial (p1, p2)
Camera2.k1: -0.0495
Camera2.k2: 0.1074
Camera2.k3: -0.0570
Camera2.p1: 0.000049928 # 4.2246e-04
Camera2.p2: -0.0012

Camera.width: 800
Camera.height: 600

Camera.fps: 60
Camera.RGB: 0

Stereo.ThDepth: 40.0

Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [
      1.0000, 0.0002, 0.0012, -0.2157049,
      -0.0002, 1.0000, 0.0031, 0.0001065,
      -0.0012, -0.0030, 1.0000, 0.0008752,
      0, 0, 0, 1]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0