%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Image rescaled to 800 x 600
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 432.25
Camera1.fy: 575.48
Camera1.cx: 404.28
Camera1.cy: 324.18

Camera1.k1: -0.0064854 
Camera1.k2: 0.057725
Camera1.k3: -0.050968
Camera1.p1:-0.0013121
Camera1.p2: -0.0018103


# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Camera resolution
Camera.width: 800
Camera.height: 600

Stereo.ThDepth: 60.0

IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [-0.0014407,  -0.99985778, -0.01680316, -0.06134912,
        -0.07741968,  0.01686426, -0.99685595, -0.01465666,
         0.99699755, -0.00013527,-0.07743296, -0.09588577,
         0.0,          0.0,          0.0,          1.0     ]

# IMU noise
IMU.NoiseGyro: 8.437606694181497e-05
IMU.NoiseAcc: 0.0008621824075684253
IMU.GyroWalk: 2.0569571591853487e-06
IMU.AccWalk: 1.7510714331378923e-05
IMU.Frequency: 100.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid     
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid    
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast            
ORBextractor.iniThFAST: 18
ORBextractor.minThFAST: 6

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0